* Cookbook

For Luc and Marc

** Introduction

Inexpensive, fast, delicious food. You can have all three if you make it yourself. This book has basic recipes that are can be stored, reheated and combined. They can be easily packed for lunch at work.

Before we start, here are important things to remember.

First, cook before you're hungry. Cook in advance, when you have time. Cook after dinner, or during the weekends.

Second, cook in batches, and have at least three meals prepared ahead of time.

Third, plan your menus for the week, and make your shopping list accordingly.


** Chicken and rice

The basic recipe is declined in very many ways around the world. Here are a few variations that are easy to prepare and reuse.

*** Basic recipe: grilled chicken over rice

Ingredients (three portions):
- Six chicken thighs, boneless skinless
- 2 cups white rice
- Salt, pepper
- Green onions, or cilantro, or parsley
- Soy sauce
- Your favorite dressing sauce: sriracha, spicy mayo, japanese BBQ sauce...

First, preheat your oven at 400F.

Then, let's make the rice. You'll use  white rice. Basmati and Calrose are great general-purpose choices. In a pot, put one measure of rice, and one-and-a-half measure of water. For a couple days worth of rice, I'll use two cups of rice and three cups of water. Add two pinches of salt. Bring to a light boil, then reduce to a simmer on your lowest stove setting. Cover, and leave on for twenty minutes. Turn off the stove, let it rest for another ten minutes. You're done.

Then, on to the chicken. Use six boneless and skinless chicken thighs, that will last you a couple days. Put the thighs on the cooking sheet in a heap. Top it off with a spoonful of oil, four big pinches of salt, and cracked pepper. You can also add in gochugaru or smoked paprika for extra umami. Rub it all together, then lay down the individual thighs, with space in between. Cook 15 minutes on one side, then 10 minutes on the other side. These are starting values, adjust them next time based on your personal preference. Take it out of the oven, let rest for 5 mminutes.

Now let's plate. Put two scoops of rice in a bowl. Cut two chicken thighs in strips, lay over the rice. Chop one green onion (or a small fistful of cilantro, or italian parsley), sprinkle on the bowl. Pour a tablespoon of soy sauce. Finish with a few dashes of your favorite dressing sauce. My sons like japanese BBQ sauce and spicy mayo, I like sriracha.

With five minutes of hands-on work, you just made the most delicious bowl of chicken and rice. You can reuse the leftover in many ways, which we'll explore below.

*** Hainanese chicken and rice

There's an even easier way to make chicken and rice, with a single pot. Originally from Hainan in China, the recipe became Singapore's national dish. Here's a basic version.

Ingredients (three portions):
- Six chicken thighs, skinless boneless
- Two cups rice
- Green onions (or other herbs, like above)
- One ounce of fresh ginger (big as thumb)
- Fish sauce
- Soy sauce
- Toasted sesame seed oil

In a pot, put two cups of rice and three cups of water. Chop ginger in roughly 1/8 inch slices, like three quarters thick, add to pot. Add three tablespoons of soy sauce, a dash of fish sauce, a dash of toasted sesame seed oil. Add two green onions cut in half. Add the chicken thighs, mix it all together. Bring to a light boil and taste. The broth should be lightly salty, add salt if needed. Bring stove to lowest setting. Cover and cook for 25 minutes.

With a pair of thongs, pull out the chicken thighs. Then pull out the ginger slices, and discard them. You can pull out the cooked green onions and discard them, or chop them and mix them in with the rice. The plating is identical to the previous recipe: scoop rice in a bowl, put sliced chicken on top, add green onions or other herbs, finish with soy sauce and your favorite dressing.

*** Chicken curry

This is an extension of our first recipe ("grilled chicken over rice"). You'll first want to make the rice and grill the chicken. While they're cooking, you'll prepare your curry.

Ingredients (3 portions):
- One yellow onion
- One can coconut cream, unsweetened
- One ounce fresh ginger (big like thumb)
- One teaspoon cumin seeds
- One teaspoon curry powder
- One teaspoon turmeric powder
- Green onions

Dice the onion. In a pot, heat up a big dash of oil until it gets nice and hot. Add cumin seeds, let them crackle for a few seconds. Then add your curry powder and turmeric powder. Mix them in with the hot oil, and let them darken for a minute. Then toss in the diced onions. Mix in, let the onions take color for 5 to 10 minutes, stirring occasionally. Then add the can of coconut cream. Bring to a light boil, reduce to a simmer, cover for 10 minutes. Then dice the grilled chicken and add to the curry. Now you're ready to plate, two scoops of rice in each bowl, ladle in some curry, then cover in chopped green onions or your herb of choice.

** Packing, plating and herbs

Ideally, when mealtime comes, you have should have no cooking to do. Aim to have all the ingredients ready, cooked ahead of time, stored in the fridge.

If you're eating lunch at work, pack your lunch in the morning, or the night before. If you're eating at home, all you have is plate your meal and reheat it in microwave.

The secret to make your plate look amazing, and taste delicious, is herbs. Don't mereley sprinkle them on your plate, put a lot on, almost like a vegetable. When packing your lunch, put the herbs in. It's OK if they go in the microwave when you reheat it. Whean eating at home, I put the herbs in after reheating my plate.

*** Green onions

They're delicious, with a great crunchy texture. Just cut out the roots, and use the entire plant, white and green parts. Chop not too thin (1/8 to 1/4 inch) so that they retain some bite. The downside is that they don't keep very long. To increase their shelf life, unbundle them before storing, otherwise the humidity will make them wilt fasyer. Then leave them in a paper bag in the fridge.

*** Parsley

Parsley comes in two sorts, italian and curly. Italian parsley has straight leaves. Both look great on a plate. They have a mild taste, and they keep well in the fridge, typically more than a week.

*** Cilantro

Cilantro has a unique flavor that goes well with Asian and latino-american dishes. Beware that it tastes like soap to some people, because of a genetic

** Green vegetables

*** Broccoli

Wash one head of broccoli. Cut flower into bite-size branches, cutting the thicker ones in half. Drizzle 1 tablespoon oil, sprinkle salt, pepper, gochugaru. Microwave for 3 minutes.

*** Asparagus

For green asparagus, trim the lower third, or remove the thick skin with a vegetable peeler. Drizzle 1 tablespoon oil, sprinkle salt, pepper, gochugaru. Microwave for 3 minutes.

*** Bok choi

Wash, cut in 1/2 inch slices lengthwise. Microwave for 4 minutes. Eat over rice or steel cut oats. Flavor with soy sauce or ponzu.

*** Leek

Trim roots. Cut in half lengthwise. Wash, making sure to remove dirt between outer layers. Chop in 1/4 inch slices. Drizzle oil, salt, pepper, gochugaru or smoked paprika, dash toasted sesame oil. Microwave for 3 minutes.

*** Dino kale

Trim stems. Rinse unter faucet, shake dry. Chop into narrow 1/8 inch strips, cutting perpendicular to main stem. Drizzle oil, salt, pepper, gochugaru or smoked paprika, dash toasted sesame oil. Microwave for 3 to 5 minutes.

*** Brussel sprouts

Warm up oven at 400 degrees. Rinse, trim stem, cut in quarters. On baking sheet, toss with 2 tablespoons of oil, generous amount of salt, pepper. It does need more salt than other greens. Spread on baking sheet, a bit spaced out. 30 minutes in the oven on top rack. Then toss, and put in for another 15 minutes, more if neeed.


** Meat

*** Ground beef

Preheat your oven at 400F. Dice two onions, toss on baking sheet, mix in one tablespoon of oil, pepper, salt, smoked paprika or gochugaru. Spread evenly on baking sheet and bake for about 20mns, until onions are golden brown. Then mix in the ground beef, adding more salt if needed. Spread evenly, and bake for another 10 to 12 minutes, until the ground beef is fully cooked. Break larger chunks using a wooden spoon. Add more salt if needed.

Serve over any starch: potatoes, sweet potatoes, rice...
Makes a good chili con carne if you combine with the black bean recipe below.
Also, try spreading some on your omelet.

*** Pork chops

**** Method 1: skillet

Preheat your oven at 350F. Warm up two tablespoons of oil in your skillet. Salt/pepper the meat. Sear your pork chops on both sides until golden brown, about 3 to 5 minutes on each side. Hint: don't crowd the pan! For best results, make sure your pork chops are spread at least one inch apart from each other. Then put your skillet in the oven for 5 to 10 minutes, depending how thick your pork chop is. Take it out of the oven, let rest for at least 5mns. You're done.

**** Method 2: oven broiler

This is handy if you want to prepare larger batches. Start your oven on high broiler. Salt/pepper the meat. Lightly sprinkle with oil, but not too much, otherwise your kitchen will get very smoky. Put in the oven, with the meat at least 5 inches away from the broiler element. Careful, some oven broilers put out a lot of heat. Sear a couple minutes on each side, until golden brown. Turn off the broiler, start your oven at 350F. Finish cooking your pork chops in the bottom rack of the oven for 5 to 10 minutes, depending on how thick your pork chops are. Take them out of the oven, let rest for at least 5 minutes. You're done.

*** Sausage

Buy fresh pork sausage, quite thick (1 to 1.5"). Mild italian works too. If you can only find pre-cooked sausage, try kielbasa. Simply put in baking sheet under the broiler, a few minutes on each side until golden brown. Then turn off the broiler, move the baking sheet to the bottom of the oven, let sit for 10mns with oven door closed.

Serve with any starch and grilled vegetable. Delicious in omelets. Or sliced, with beans.

** Starches

*** Potatoes

Buy fingerling potaoes and use them whole, skin on. Or buy Yukon Golds, and chop them in 1.5-inch cuboids. In a bowl, toss with a bit of oil, good amount of salt, pepper, gochugaru or smoked paprika.

**** Method 1: microwave oven

Microwave for 3mns at a time. Toss and test with a fork between each 3mn run. It will take 6 to 9 minutes to get them fully cooked thru.

**** Method 2: oven

Preheat oven at 400F. Spread potatoes on baking sheet, mix with 2 tablspoons of oil, good amount of salt, pepper, gochugaru or smoked paprika. Space out the chunks, ideally they won't touch. That will give you better Maillard. Bake 20 minutes, turn/toss the potatoes, bake another 15mns or so.

*** Sweet potatoes

Preheat oven at 400F. Put 2 tablespoons of oil in a skillet, warm it up on the stove. Put sweet potatoes on skillet, sprinkle salt and pepper, then straight in the oven. Turn after 30 minutes, then another 30mns in oven. 60 minutes total. Check for doneness with a fork.

*** Dhal

Super versatile, can be a meal by itself, or combined with a protein and a green vegetable.

Ingredients (3 portions):
- 1 cup red lentils
- 3 cups of water
- 1 onion
- 1 14.5oz can diced tomatoes (fire-roasted even better)
- curry spices: cumin seed, tumeric, curry powder
- fish sauce
- optional: 8oz frozen spinach

Dice the onion. In cooking pot, warm up 3 tablespoons of oil. Put half a teaspoon of cumin seed, let it sizzle for a minute. Then add a teaspoon of tumeric, and one of curry powder. Mix in with oil, let color darken a litle. Add diced onion, let them brown for a bit. Add 1 can diced tomatoes, mix them in with the onion. Then add 1 cup red lentils, 3 cups of water, 1 dash of fish sauce, 1 teaspoon of salt. Bring to a light boil, reduce to lowest stove setting. Cover and simmer for 30mns. Stir and check salt levels every 10mns. If using spinach, blend it in the dhal 5 minutes before the end of cooking time, turning up the stove if needed.

*** Beans

Can be a meal by itself, or combined with a protein and a green vegetable.
Try it with white beans (Pinto or Navy), or with black beans.

Ingredients:
- 1 14.5oz can of white beans (Navy and Pinto also work great)
- 1 14.5oz can of diced tomatoes (fire-roasted even better)
- 1 onion
- fish sauce
- gochujang

Dice one onion. Warm up 2 tablespoons of oil in cooking pot. Cook onions until nice and brown. Add diced tomatoes. Bring to a gentle boil, then add 1 tablespoon gochujang, 1 dash fish sauce, salt as needed. Simmer for 10mns. Add beans and their liquid. Don't discard the liquid! It's delicious. Cook for another 10mns. Adjust salt levels.

*** Overnight steel cut oats

Great for breakfast with sugar and butter, in yogurt, or savory as a substitute for rice. Not to be confused with rolled oats.
In a cooking pot, put one cup of steel cut oats, three cups water, big pinch of salt. Bring to a rolling boil, until foaming starts. Stir, reduce to a simmer and cover. Cook for 10 minutes. Turn off the stove. Leave covered pot on stover overnight. Oats will be perfect in the morning.

*** Quinoa

*** Polenta

** Eggs

*** Hard boiled

*** Omelets

** Pasta

** Ratatouille

** Fish

** Sandwiches

** Breakfast

** Planning: making menus and shopping list

** Food safety - cleaning up

** Maintenance
- Skillet
- Knives

** Nutrition
